spring:
  devtools:
    livereload:
      enabled: true # ??? ?? ??? ?? ??
    restart:
      enabled: true # ?? ??? ?? ???
  profiles:
    active: api
  jpa:
    # ?? ?? ??
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console